---
- name: update all packages
  apt:
    update_cache: true
    upgrade: dist
  when: raspi_config_update_packages

- name: sets the timezone
  timezone:
    name: "{{ raspi_config_timezone }}"
  notify: restart timezone dependent services

- name: ensure filesystem is resized
  expand_fs:
  when: raspi_config_expanded_filesystem
  register: expand_fs_output

- name: filesystem expand non-action check
  debug:
    msg: "{{ expand_fs_output.stderr }}"
  when: "raspi_config_expanded_filesystem and expand_fs_output.stderr.startswith('WARN')"
  changed_when: "True"      

- name: ensure mem split
  pi_boot_config:
    config_vals: "gpu_mem={{ raspi_config_memory_split_gpu }}"
  notify:
    - apply raspi-config
    - reboot